<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Slo248.Net.DomainDrivenDesign</RootNamespace>

    <!-- Package Metadata (Required for NuGet) -->
    <PackageId>Slo248.Net.DomainDrivenDesign</PackageId>
    <Version>1.0.1</Version>
    <Authors>Slo248</Authors>
    <Description>A Domain-Driven Design library providing base classes and interfaces for aggregate roots, entities, and domain events.</Description>
    <RepositoryUrl>https://github.com/slo248/Net.Basis</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>DDD;DomainDrivenDesign;AggregateRoot;Entity;DomainEvent</PackageTags>
    <License>MIT</License>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <PackageIcon>slo248-nuget-icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Update="slo248-nuget-icon.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Slo248.Net.Cqrs\Slo248.Net.Cqrs.csproj"/>
  </ItemGroup>

</Project>
